### ISSUE TITLE
No Babel configuration?

### ISSUE THREAD

**Issue by victorlin** [nano-react-app/template-ts#10]
From the [README](https://github.com/nano-react-app/template-ts/blob/a9b35099ca7d7caf90052feb1fa0e7e1885f31d8/README.md?plain=1#L41):

> The Babel configuration lives inside `package.json` and will override an external `.babelrc` file, so if you want to use `.babelrc` remember to delete the `babel` property inside `package.json`.

However, that section was removed in 298da61c53ee731205556f19e302267dadddccaf.

**Comment by mgreasly** [comment]
Sounds like we can close this issue then as resolved during the update to Vite.
