### ISSUE TITLE
Typechecking w/ Vite

### ISSUE THREAD

**Issue by kotx** [nano-react-app/template-ts#3]
In the README:
> Unforunately, Parcel does not perform typechecking. So you will need to make use of the typecheck and typewatch scripts above.

This seems to now be outdated since we're using Vite. Should be updated maybe? I don't think manual typechecking is required anymore, though I could be wrong/it could require extra config.

**Comment by kotx** [comment]
Seems typechecking requires another Vite plugin? Dunno. Maybe we just need to update the README to say Vite instead of Parcel.

**Comment by mgreasly** [comment]
Thanks @kotx - I missed that reference when we updated the template. I've updated the reference with a quick PR. I don't know what plugin Vite needs for typechecking etc., but I will take a look to see if it's something we can include.
